routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ProductsController;
use App\Http\Controllers\GroupsController;
use App\Http\Controllers\LoadingsController;
use App\Http\Controllers\TeamsController;
use App\Http\Controllers\BrokenTypesController;
use App\Http\Controllers\ContainerTypeController;
use App\Http\Controllers\CustomerTypesController;
use App\Http\Controllers\ReportsController;
use App\Http\Controllers\MasterPlansController;
use App\Http\Controllers\UsersController;
use App\Http\Controllers\ShipPlansController;
use App\Http\Controllers\ListLoadController;
use App\Http\Controllers\ListLoadDetController;
use App\Http\Controllers\CropsController;
use App\Http\Controllers\ExtWhsController;
use App\Http\Controllers\LoadingCarriesController;
use App\Http\Controllers\CheckPointsController;
use App\Http\Controllers\CheckSetsController;
use App\Http\Controllers\CheckQuestionsController;
use App\Http\Controllers\CheckAnswersController;
use App\Http\Controllers\DriversController;
use App\Http\Controllers\UploadDeliveryPlansController;
use App\Http\Controllers\CheckPointPublicController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/checkscan', [CheckPointPublicController::class, 'scan']);


Route::get('/', [LoadingsController::class, 'list']);

Route::get('/userdatas/changepass', [UsersController::class, 'changepass'])->name('userdatas.changepass');
Route::post('/userdatas/changepassAction', [UsersController::class, 'changepassAction'])->name('userdatas.changepassaction');
Route::get('/user_importView', [UsersController::class, 'importExportView'])->name('user_importView');
Route::post('/userdatas/import', [UsersController::class, 'import'])->name('user_import');
Route::resource('userdatas', UsersController::class);
Route::get('/product_importView', [ProductsController::class, 'importExportView'])->name('product_importView');
Route::post('/products/import', [ProductsController::class, 'import'])->name('product_import');
Route::get('/products/getbyid/{id}', [ProductsController::class, 'getById'])->name('products.getById');
Route::get('/drivers', [DriversController::class, 'index'])->name('drivers.index');
Route::resource('uploaddeliveryplans', UploadDeliveryPlansController::class);


Route::prefix('admin')->group(function () {
    Route::get('check_points/qrcode', [CheckPointsController::class, 'qrcode'])->name('check_points.qrcode');
    Route::resource('check_points', CheckPointsController::class);
    Route::resource('check_sets', CheckSetsController::class);
    Route::prefix('{check_set_id}')->group(function () {
        Route::resource('check_questions', CheckQuestionsController::class);
    });
});

Route::prefix('chkpoint/{loading_id}')->group(
    function () {
        Route::get('answers/scan', [CheckAnswersController::class,'scan'])->name('answers.scan');
        Route::get('answers/createall', [CheckAnswersController::class, 'createAll'])->name('answers.createAll');
        Route::post('answers/storeall', [CheckAnswersController::class, 'storeAll'])->name('answers.storeAll');
        Route::resource('answers', CheckAnswersController::class);
});

Route::resource('products', ProductsController:: class);
Route::resource('crops', CropsController::class);
Route::resource('ext_whs', ExtWhsController::class);
Route::resource('groups', GroupsController::class);
Route::resource('planships', ShipPlansController::class);
Route::get('/team_importView', [TeamsController::class, 'importExportView'])->name('team_importView');
Route::post('/teams/import', [TeamsController::class, 'import'])->name('team_import');
Route::resource('teams', TeamsController::class);
Route::resource('broken-types', BrokenTypesController::class);
Route::resource('customer-types', CustomerTypesController::class);
Route::resource('container-types', ContainerTypeController::class);

Route::get('/master-plans/createdetail/{master_plan_m_id}', [MasterPlansController::class, 'createdetail'])->name('master-plans.createdetail');
Route::post('/master-plans/createdetailAction/{master_plan_m_id}', [MasterPlansController::class, 'createdetailAction'])->name('master-plans.createdetailAction');
Route::get('/master-plans/editdetail/{id}', [MasterPlansController::class, 'editdetail'])->name('master-plans.editdetail');
Route::post('/master-plans/editdetailAction/{id}', [MasterPlansController::class, 'editdetailAction'])->name('master-plans.editdetailAction');
Route::get('/master-plans/deletedetail/{id}', [MasterPlansController::class, 'deletedetail'])->name('master-plans.deletedetail');

Route::resource('master-plans', MasterPlansController::class);

Route::get('/loadings', [LoadingsController::class, 'list'])->name('loadings.index');
Route::get('/loadings/create', [LoadingsController::class, 'create'])->name('loadings.create');
Route::post('/loadings/createAction', [LoadingsController::class, 'createAction'])->name('loadings.createaction');
Route::get('/loadings/edit/{id}', [LoadingsController::class, 'edit'])->name('loadings.edit');
Route::post('/loadings/editAction/{id}', [LoadingsController::class, 'editAction'])->name('loadings.editaction');
Route::get('/loadings/show/{id}', [LoadingsController::class, 'show'])->name('loadings.show');
Route::get('/loadings/realtime/{id}', [LoadingsController::class, 'realtime'])->name('loadings.realtime');
Route::get('/loadings/realtimeno/{id}', [LoadingsController::class, 'realtimeno'])->name('loadings.realtimeno');
Route::get('/loadings/sent_mail', [LoadingsController::class, 'sent_mail'])->name('loadings.sent_mail');
Route::get('/loadings/sent_mail_extImage', [LoadingsController::class, 'sent_mail_extImage'])->name('loadings.sent_mail_extImage');

// Route::get('/loadings/downloadPDF/{id}', [LoadingsController::class, 'downloadPDF'])->name('loadings.downloadPDF');
Route::post('/loadings/load_reason', [LoadingsController::class, 'load_reason'])->name('loadings.load_reason');
Route::get('/loadings/clone/{id}', [LoadingsController::class, 'clone'])->name('loadings.clone');
Route::post('/loadings/cloneAction/{id}', [LoadingsController::class, 'cloneAction'])->name('loadings.cloneAction');

Route::get('/loadings/getrealcounter/{id}', [LoadingsController::class, 'getrealcounter'])->name('loadings.getrealcounter');
Route::get('/loadings/edit/{id}', [LoadingsController::class, 'edit'])->name('loadings.edit');
Route::get('/loadings/delete/{id}', [LoadingsController::class, 'delete'])->name('loadings.destroy');
Route::get('/loadings/planload/{id}', [LoadingsController::class, 'planload'])->name('loadings.planload');
Route::post('/loadings/planloadAction/{id}', [LoadingsController::class, 'planloadAction'])->name('loadings.planloadaction');
Route::get('/loadings/createdetail/{id}', [LoadingsController::class, 'createdetail'])->name('loadings.createdetail');
Route::post('/loadings/createdetailAction/{id}', [LoadingsController::class, 'createdetailAction'])->name('loadings.createdetailaction');
Route::get('/loadings/editdetail/{id}', [LoadingsController::class, 'editdetail'])->name('loadings.editdetail');
Route::post('/loadings/editdetailAction/{id}', [LoadingsController::class, 'editdetailAction'])->name('loadings.editdetailaction');
Route::get('/loadings/deletedetail/{id}', [LoadingsController::class, 'deletedetail'])->name('loadings.deletedetail');
Route::get('/loadings/planloadview/{id}', [LoadingsController::class, 'planloadview'])->name('loadings.planloadview');
Route::get('/loadings/changestage/{id}/{stage}', [LoadingsController::class, 'changestage'])->name('loadings.changestage');
Route::get('/loadings/entersection1/{id}', [LoadingsController::class, 'entersection1'])->name('loadings.entersection1');
Route::post('/loadings/entersection1Action/{id}', [LoadingsController::class, 'entersection1Action'])->name('loadings.entersection1action');
Route::get('/loadings/entersection2/{id}', [LoadingsController::class, 'entersection2'])->name('loadings.entersection2');
Route::post('/loadings/entersection2Action/{id}', [LoadingsController::class, 'entersection2Action'])->name('loadings.entersection2action');
Route::get('/loadings/entersection3/{id}', [LoadingsController::class, 'entersection3'])->name('loadings.entersection3');
Route::post('/loadings/entersection3Action/{id}', [LoadingsController::class, 'entersection3Action'])->name('loadings.entersection3action');
Route::get('/loadings/entersection4/{id}', [LoadingsController::class, 'entersection4'])->name('loadings.entersection4');
Route::post('/loadings/entersection4Action/{id}', [LoadingsController::class, 'entersection4Action'])->name('loadings.entersection4action');
Route::get('/loadings/closeload/{id}', [LoadingsController::class, 'closeload'])->name('loadings.closeload');
Route::get('/loadings/usemasterplan/{id}', [LoadingsController::class, 'usemasterplan'])->name('loadings.usemasterplan');
Route::post('/loadings/usemasterplanAction/{id}', [LoadingsController::class, 'usemasterplanAction'])->name('loadings.usemasterplanaction');
Route::get('/loadings/entercountermanual/{id}', [LoadingsController::class, 'entercountermanual'])->name('loadings.entercountermanual');
Route::post('/loadings/entercountermanualAction/{id}', [LoadingsController::class, 'entercountermanualAction'])->name('loadings.entercountermanualAction');
Route::get('/loadings/search', [LoadingsController::class, 'searchLoading'])->name('loadings.search');
Route::get( '/loadings/searchview/{id}', [LoadingsController::class, 'viewLoadingData'])->name('loadings.searchview');
Route::get('/loadings/searchviewextimage/{id}', [LoadingsController::class, 'viewLoadingDataExtImage'])->name('loadings.searchviewextimages');

app/Models/CheckPoint.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class CheckPoint extends Model
{
    use HasFactory;

    protected $fillable = [
            'name',
            'desc',
            'lat',
            'lng',
            'status'];

    public function checkanswers()
    {
        return $this->hasMany('App\Models\CheckAnswer', 'check_point_id');
    }
}

app/Http/Controllers/CheckPointsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\CheckPoint;

class CheckPointsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public $mainnav = 'BaseData';
    public $namenav = 'check_points';
    public $statusList = [
        'Active' => 'Active',
        'Inactive' => 'Inactive'
    ];


    public function index(Request $request)
    {
        $keyword = $request->get('search');
        $perPage = 10;

        if (!empty($keyword)) {
            $checkpoints = CheckPoint::where('name', 'like', '%' . $keyword . '%')
                ->paginate($perPage);
        } else {
            $checkpoints = CheckPoint::latest()->paginate($perPage);
        }

        $mainnav = $this->mainnav;
        $namenav = $this->namenav;
        return view('admin.checkpoints.index', compact('checkpoints', 'mainnav', 'namenav'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $mainnav = $this->mainnav;
        $namenav = $this->namenav;
        $statusList = $this->statusList;
        return view('admin.checkpoints.create', compact('mainnav', 'namenav', 'statusList'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $requestData = $request->all();

        $validated = $request->validate([
            'name' => 'required|unique:check_points',
        ]);

        CheckPoint::create($requestData);

        return redirect('admin/check_points')->with('flash_message', ' added!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $mainnav = $this->mainnav;
        $namenav = $this->namenav;
        $checkpoint = CheckPoint::findOrFail($id);
        return view('admin.checkpoints.view', compact('checkpoint', 'mainnav', 'namenav'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $mainnav = $this->mainnav;
        $namenav = $this->namenav;
        $checkpoint = CheckPoint::findOrFail($id);

        $statusList = $this->statusList;
        return view('admin.checkpoints.edit', compact('checkpoint', 'mainnav', 'namenav', 'statusList'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $requestData = $request->all();


        $checkpoint = CheckPoint::findOrFail($id);

        $validated = $request->validate([
            'name' => 'required|unique:check_points,name,' . $checkpoint->id,
        ]);


        $checkpoint->update($requestData);

        return redirect('admin/check_points')->with('flash_message', ' updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $countcandelete = CheckPoint::findOrFail($id)->checkanswers()->count();

        if ($countcandelete == 0) {
            CheckPoint::destroy($id);
            return redirect('admin/check_points')->with('flash_message', ' deleted!');
        } else {
            return back()->with('error', 'Delete not successfully');
        }
    }

    public function qrcode(){

        $checkpoints = CheckPoint::all();
        $mainnav = $this->mainnav;
        $namenav = $this->namenav;
        return view('admin.checkpoints.qrcode', compact('checkpoints', 'mainnav', 'namenav'));
    }
}

resources/views/admin/checkpoints/create.blade.php
@extends('layouts.main')

@section('content')

    <div class="page-heading">
        <h3>{{ __('จัดการ จุดตรวจ') }}</h3>
        <div class="pull-right">
            <a class="btn btn-success" href="{{ route('check_points.index') }}">Back</a>
        </div>
    </div>
    <div class="page-content">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">{{ __('สร้าง จุดตรวจ ใหม่') }}</div>

                    <div class="card-body">
                        <form method="POST" action="{{ route('check_points.store') }}">
                            @csrf


                            <div class="form-product row">
                                <label for="name" class="col-md-2 col-form-label text-md-right">{{ __('จุดตรวจ name') }}</label>

                                <div class="col-md-4">
                                    <input id="name" type="text" class="form-control @error('name') is-invalid @enderror"
                                        name="name" value="{{ old('name') }}" required >

                                    @error('name')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                                <label for="status" class="col-md-2 col-form-label text-md-right">{{ __('Status') }}</label>

                                <div class="col-md-4">
                                     {{ Form::select('status', $statusList , null, ['placeholder' => '==เลือก==', 'class' => 'form-control']) }}

                                    @error('status')
                                        <span class="invalid-feedback" role="status">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>

                            </div>
                            <div class="form-product row">
                                <label for="lat" class="col-md-2 col-form-label text-md-right">{{ __('Latitude') }}</label>

                                <div class="col-md-4">
                                    <input id="lat" type="text" class="form-control @error('lat') is-invalid @enderror"
                                        name="lat" value="{{ old('lat') }}" required >

                                    @error('lat')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                                <label for="lng" class="col-md-2 col-form-label text-md-right">{{ __('Logntitude') }}</label>

                                <div class="col-md-4">
                                    <input id="lng" type="text" class="form-control @error('lng') is-invalid @enderror"
                                        name="lng" value="{{ old('lng') }}" required >

                                    @error('lng')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-product row">
                                <label for="desc" class="col-md-2 col-form-label text-md-right">{{ __('Desc') }}</label>

                                <div class="col-md-10">
                                    <input id="desc" type="text" class="form-control @error('desc') is-invalid @enderror"
                                        name="desc" value="{{ old('desc') }}">

                                    @error('desc')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-product row mb-0">
                                <div class="col-md-6 offset-md-2">
                                    <button type="submit" class="btn btn-primary">
                                        {{ __('Create') }}
                                    </button>
                                </div>
                            </div>


                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/checkpoints/edit.blade.php
@extends('layouts.main')

@section('content')

    <div class="page-heading">
        <h3>{{ __('จัดการ จุดตรวจ') }}</h3>
        <div class="pull-right">
            <a class="btn btn-success" href="{{ route('check_points.index') }}">Back</a>
        </div>
    </div>
    <div class="page-content">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">{{ __('แก้ไข จุดตรวจ #').$checkpoint->id }}</div>

                    <div class="card-body">
                        <form action="{{ route('check_points.update', $checkpoint->id) }}" method="POST">
                            @csrf

                            @method('PUT')

                            <div class="form-product row">
                                <label for="name" class="col-md-2 col-form-label text-md-right">{{ __('จุดตรวจ name') }}</label>

                                <div class="col-md-4">
                                    <input id="name" type="text" class="form-control @error('name') is-invalid @enderror"
                                        name="name" value="{{ $checkpoint->name }}" required >

                                    @error('name')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                                <label for="status" class="col-md-2 col-form-label text-md-right">{{ __('Status') }}</label>

                                <div class="col-md-4">
                                     {{ Form::select('status', $statusList , $checkpoint->status, ['placeholder' => '==เลือก==', 'class' => 'form-control']) }}

                                    @error('status')
                                        <span class="invalid-feedback" role="status">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>

                            </div>
                            <div class="form-product row">
                                <label for="lat" class="col-md-2 col-form-label text-md-right">{{ __('Latitude') }}</label>

                                <div class="col-md-4">
                                    <input id="lat" type="text" class="form-control @error('lat') is-invalid @enderror"
                                        name="lat" value="{{ $checkpoint->lat }}" required >

                                    @error('lat')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                                <label for="lng" class="col-md-2 col-form-label text-md-right">{{ __('Logntitude') }}</label>

                                <div class="col-md-4">
                                    <input id="lng" type="text" class="form-control @error('lng') is-invalid @enderror"
                                        name="lng" value="{{ $checkpoint->lng }}" required >

                                    @error('lng')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-product row">
                                <label for="desc" class="col-md-2 col-form-label text-md-right">{{ __('Desc') }}</label>

                                <div class="col-md-10">
                                    <input id="desc" type="text" class="form-control @error('desc') is-invalid @enderror"
                                        name="desc" value="{{ $checkpoint->desc }}">

                                    @error('desc')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-product row mb-0">
                                <div class="col-md-6 offset-md-2">
                                    <button type="submit" class="btn btn-primary">
                                        {{ __('Edit') }}
                                    </button>
                                </div>
                            </div>


                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/checkpoints/index.blade.php
@extends('layouts.main')

@section('content')
    @if(Session::has('success'))
        <div><h3> {{ Session::get('success') }}</h3></div>
    @endif
    @if(Session::has('error'))
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            <strong>{{ Session::get('error') }}</strong>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    @endif
    <div class="page-heading">
        <h3>{{ __('จัดการ จุดตรวจ') }}</h3>
    </div>
    <div class="page-content">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <a class="btn btn-success" href="{{ route('check_points.create') }}">สร้าง จุดตรวจ</a>  <a class="btn btn-success" href="{{ route('check_points.qrcode') }}" target="_blank">พิมพ์ qrcode</a>
                    </div>
                    <div class="p-2">
                    <form method="GET" action="{{ route('check_points.index') }}" accept-charset="UTF-8" class="form-inline my-2 my-lg-0 float-right" role="search">
                            <div class="input-group">
                                <input type="text" class="form-control" name="search" placeholder="Search..." value="{{ request('search') }}">
                                <span class="input-group-append">
                                    <button class="btn btn-secondary" type="submit">
                                        Search
                                    </button>
                                </span>
                            </div>
                        </form>
                    </div>
                    <div class="card-body">
                        @if ($message = Session::get('success'))
                            <div class="alert alert-success">
                                <p>{{ $message }}</p>
                            </div>
                        @endif

                        <table class="table table-bordered">
                            <tr>
                                <th>ชื่อ</th>
                                <th>รายละเอียด</th>
                                <th>latitude / longtitude</th>
                                <th>status</th>
                                <th></th>
                            </tr>
                            @foreach ($checkpoints as $checkpoint)
                                <tr>
                                    <td>{{ $checkpoint->name }}</td>
                                    <td>{{ $checkpoint->desc }}</td>
                                    <td>{{ $checkpoint->lat }} / {{ $checkpoint->lng }}</td>
                                    <td>{{ $checkpoint->status }}</td>
                                    <td>
                                        <a class="btn btn-info" href="{{ route('check_points.show', $checkpoint->id) }}">แสดงข้อมูล</a>
                                        <a class="btn btn-primary" href="{{ route('check_points.edit', $checkpoint->id) }}">แก้ไข</a>
                                        <form action="{{ route('check_points.destroy', $checkpoint->id) }}" method="POST">
                                            @csrf
                                            @method('DELETE')
                                            <button type="submit" class="btn btn-danger">ลบ</button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                        </table>
                        <div class="pagination-wrapper"> {!! $checkpoints->appends(['search' => Request::get('search')])->render() !!} </div>
                    </div>
                </div>
            </div>
        </div>
    </div>




@endsection

resources/views/admin/checkpoints/view.blade.php
@extends('layouts.main')

@section('content')

    <div class="page-heading">
        <h3>{{ __('จัดการ จุดตรวจ') }}</h3>
        <div class="pull-right">
            <a class="btn btn-success" href="{{ route('check_points.index') }}">Back</a>
        </div>
    </div>
    <div class="page-content">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">{{ __('แสดงข้อมุล จุดตรวจ') }}</div>

                    <div class="card-body">
                        @if ($message = Session::get('success'))
                            <div class="alert alert-success">
                                <p>{{ $message }}</p>
                            </div>
                        @endif

                        <table class="table table-bordered">
                            <tr>
                                <th>name</th>
                                <td>{{ $checkpoint->name }}</td>
                            </tr>
                            <tr>
                                <th>Latitide</th>
                                <td>{{ $checkpoint->lat }}</td>
                            </tr>
                            <tr>
                                <th>Longtitide</th>
                                <td>{{ $checkpoint->lng }}</td>
                            </tr>
                            <tr>
                                <th>desc</th>
                                <td>{{ $checkpoint->desc }}</td>
                            </tr>
                            <tr>
                                <th>status</th>
                                <td>{{ $checkpoint->status }}</td>
                            </tr>
                            <tr>
                                <th>Action</th>
                                <td>
                                    <a class="btn btn-primary" href="{{ route('check_points.edit', $checkpoint->id) }}">แก้ไข</a>
                                    <form action="{{ route('check_points.destroy', $checkpoint->id) }}" method="POST">

                                        @csrf
                                        @method('DELETE')
                                        <button type="submit" class="btn btn-danger">ลบ</button>
                                    </form>
                                </td>
                            </tr>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>




@endsection