routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ProductsController;
use App\Http\Controllers\GroupsController;
use App\Http\Controllers\LoadingsController;
use App\Http\Controllers\TeamsController;
use App\Http\Controllers\BrokenTypesController;
use App\Http\Controllers\ContainerTypeController;
use App\Http\Controllers\CustomerTypesController;
use App\Http\Controllers\ReportsController;
use App\Http\Controllers\MasterPlansController;
use App\Http\Controllers\UsersController;
use App\Http\Controllers\ShipPlansController;
use App\Http\Controllers\ListLoadController;
use App\Http\Controllers\ListLoadDetController;
use App\Http\Controllers\CropsController;
use App\Http\Controllers\ExtWhsController;
use App\Http\Controllers\LoadingCarriesController;
use App\Http\Controllers\CheckPointsController;
use App\Http\Controllers\CheckSetsController;
use App\Http\Controllers\CheckQuestionsController;
use App\Http\Controllers\CheckAnswersController;
use App\Http\Controllers\DriversController;
use App\Http\Controllers\UploadDeliveryPlansController;
use App\Http\Controllers\CheckPointPublicController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/checkscan', [CheckPointPublicController::class, 'scan']);


Route::get('/', [LoadingsController::class, 'list']);

Route::get('/userdatas/changepass', [UsersController::class, 'changepass'])->name('userdatas.changepass');
Route::post('/userdatas/changepassAction', [UsersController::class, 'changepassAction'])->name('userdatas.changepassaction');
Route::get('/user_importView', [UsersController::class, 'importExportView'])->name('user_importView');
Route::post('/userdatas/import', [UsersController::class, 'import'])->name('user_import');
Route::resource('userdatas', UsersController::class);
Route::get('/product_importView', [ProductsController::class, 'importExportView'])->name('product_importView');
Route::post('/products/import', [ProductsController::class, 'import'])->name('product_import');
Route::get('/products/getbyid/{id}', [ProductsController::class, 'getById'])->name('products.getById');
Route::get('/drivers', [DriversController::class, 'index'])->name('drivers.index');
Route::resource('uploaddeliveryplans', UploadDeliveryPlansController::class);


Route::prefix('admin')->group(function () {
    Route::get('check_points/qrcode', [CheckPointsController::class, 'qrcode'])->name('check_points.qrcode');
    Route::resource('check_points', CheckPointsController::class);
    Route::resource('check_sets', CheckSetsController::class);
    Route::prefix('{check_set_id}')->group(function () {
        Route::resource('check_questions', CheckQuestionsController::class);
    });
});

Route::prefix('chkpoint/{loading_id}')->group(
    function () {
        Route::get('answers/scan', [CheckAnswersController::class,'scan'])->name('answers.scan');
        Route::get('answers/createall', [CheckAnswersController::class, 'createAll'])->name('answers.createAll');
        Route::post('answers/storeall', [CheckAnswersController::class, 'storeAll'])->name('answers.storeAll');
        Route::resource('answers', CheckAnswersController::class);
});

Route::resource('products', ProductsController:: class);
Route::resource('crops', CropsController::class);
Route::resource('ext_whs', ExtWhsController::class);
Route::resource('groups', GroupsController::class);
Route::resource('planships', ShipPlansController::class);
Route::get('/team_importView', [TeamsController::class, 'importExportView'])->name('team_importView');
Route::post('/teams/import', [TeamsController::class, 'import'])->name('team_import');
Route::resource('teams', TeamsController::class);
Route::resource('broken-types', BrokenTypesController::class);
Route::resource('customer-types', CustomerTypesController::class);
Route::resource('container-types', ContainerTypeController::class);

Route::get('/master-plans/createdetail/{master_plan_m_id}', [MasterPlansController::class, 'createdetail'])->name('master-plans.createdetail');
Route::post('/master-plans/createdetailAction/{master_plan_m_id}', [MasterPlansController::class, 'createdetailAction'])->name('master-plans.createdetailAction');
Route::get('/master-plans/editdetail/{id}', [MasterPlansController::class, 'editdetail'])->name('master-plans.editdetail');
Route::post('/master-plans/editdetailAction/{id}', [MasterPlansController::class, 'editdetailAction'])->name('master-plans.editdetailAction');
Route::get('/master-plans/deletedetail/{id}', [MasterPlansController::class, 'deletedetail'])->name('master-plans.deletedetail');

Route::resource('master-plans', MasterPlansController::class);

Route::get('/loadings', [LoadingsController::class, 'list'])->name('loadings.index');
Route::get('/loadings/create', [LoadingsController::class, 'create'])->name('loadings.create');
Route::post('/loadings/createAction', [LoadingsController::class, 'createAction'])->name('loadings.createaction');
Route::get('/loadings/edit/{id}', [LoadingsController::class, 'edit'])->name('loadings.edit');
Route::post('/loadings/editAction/{id}', [LoadingsController::class, 'editAction'])->name('loadings.editaction');
Route::get('/loadings/show/{id}', [LoadingsController::class, 'show'])->name('loadings.show');
Route::get('/loadings/realtime/{id}', [LoadingsController::class, 'realtime'])->name('loadings.realtime');
Route::get('/loadings/realtimeno/{id}', [LoadingsController::class, 'realtimeno'])->name('loadings.realtimeno');
Route::get('/loadings/sent_mail', [LoadingsController::class, 'sent_mail'])->name('loadings.sent_mail');
Route::get('/loadings/sent_mail_extImage', [LoadingsController::class, 'sent_mail_extImage'])->name('loadings.sent_mail_extImage');

// Route::get('/loadings/downloadPDF/{id}', [LoadingsController::class, 'downloadPDF'])->name('loadings.downloadPDF');
Route::post('/loadings/load_reason', [LoadingsController::class, 'load_reason'])->name('loadings.load_reason');
Route::get('/loadings/clone/{id}', [LoadingsController::class, 'clone'])->name('loadings.clone');
Route::post('/loadings/cloneAction/{id}', [LoadingsController::class, 'cloneAction'])->name('loadings.cloneAction');

Route::get('/loadings/getrealcounter/{id}', [LoadingsController::class, 'getrealcounter'])->name('loadings.getrealcounter');
Route::get('/loadings/edit/{id}', [LoadingsController::class, 'edit'])->name('loadings.edit');
Route::get('/loadings/delete/{id}', [LoadingsController::class, 'delete'])->name('loadings.destroy');
Route::get('/loadings/planload/{id}', [LoadingsController::class, 'planload'])->name('loadings.planload');
Route::post('/loadings/planloadAction/{id}', [LoadingsController::class, 'planloadAction'])->name('loadings.planloadaction');
Route::get('/loadings/createdetail/{id}', [LoadingsController::class, 'createdetail'])->name('loadings.createdetail');
Route::post('/loadings/createdetailAction/{id}', [LoadingsController::class, 'createdetailAction'])->name('loadings.createdetailaction');
Route::get('/loadings/editdetail/{id}', [LoadingsController::class, 'editdetail'])->name('loadings.editdetail');
Route::post('/loadings/editdetailAction/{id}', [LoadingsController::class, 'editdetailAction'])->name('loadings.editdetailaction');
Route::get('/loadings/deletedetail/{id}', [LoadingsController::class, 'deletedetail'])->name('loadings.deletedetail');
Route::get('/loadings/planloadview/{id}', [LoadingsController::class, 'planloadview'])->name('loadings.planloadview');
Route::get('/loadings/changestage/{id}/{stage}', [LoadingsController::class, 'changestage'])->name('loadings.changestage');
Route::get('/loadings/entersection1/{id}', [LoadingsController::class, 'entersection1'])->name('loadings.entersection1');
Route::post('/loadings/entersection1Action/{id}', [LoadingsController::class, 'entersection1Action'])->name('loadings.entersection1action');
Route::get('/loadings/entersection2/{id}', [LoadingsController::class, 'entersection2'])->name('loadings.entersection2');
Route::post('/loadings/entersection2Action/{id}', [LoadingsController::class, 'entersection2Action'])->name('loadings.entersection2action');
Route::get('/loadings/entersection3/{id}', [LoadingsController::class, 'entersection3'])->name('loadings.entersection3');
Route::post('/loadings/entersection3Action/{id}', [LoadingsController::class, 'entersection3Action'])->name('loadings.entersection3action');
Route::get('/loadings/entersection4/{id}', [LoadingsController::class, 'entersection4'])->name('loadings.entersection4');
Route::post('/loadings/entersection4Action/{id}', [LoadingsController::class, 'entersection4Action'])->name('loadings.entersection4action');
Route::get('/loadings/closeload/{id}', [LoadingsController::class, 'closeload'])->name('loadings.closeload');
Route::get('/loadings/usemasterplan/{id}', [LoadingsController::class, 'usemasterplan'])->name('loadings.usemasterplan');
Route::post('/loadings/usemasterplanAction/{id}', [LoadingsController::class, 'usemasterplanAction'])->name('loadings.usemasterplanaction');
Route::get('/loadings/entercountermanual/{id}', [LoadingsController::class, 'entercountermanual'])->name('loadings.entercountermanual');
Route::post('/loadings/entercountermanualAction/{id}', [LoadingsController::class, 'entercountermanualAction'])->name('loadings.entercountermanualAction');
Route::get('/loadings/search', [LoadingsController::class, 'searchLoading'])->name('loadings.search');
Route::get( '/loadings/searchview/{id}', [LoadingsController::class, 'viewLoadingData'])->name('loadings.searchview');
Route::get('/loadings/searchviewextimage/{id}', [LoadingsController::class, 'viewLoadingDataExtImage'])->name('loadings.searchviewextimages');

app/Models/CheckAnswer.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class CheckAnswer extends Model
{
    use HasFactory;

    protected $fillable = [
            'check_ans_m_id',
            'load_m_id',
            'check_point_id',
            'check_questions_id',
            'seq',
            'type_question',
            'ans1_column',
            'ans2_column',
            'ans3_column',
            'custom_f_1',
            'custom_f_2',
            'custom_f_3',
            'custom_s_1',
            'custom_s_2',
            'custom_s_3',
            'custom_t_1',
            'custom_t_2',
            'custom_t_3',
            'status'];

    public function checkans()
    {
        return $this->hasOne('App\Models\CheckAnsM', 'id', 'check_ans_m_id');
    }

    public function loadingm()
    {
        return $this->hasOne('App\Models\LoadM', 'id', 'load_m_id');
    }

    public function checkpoint()
    {
        return $this->hasOne('App\Models\CheckPoint', 'id', 'check_point_id');
    }

    public function checkquestion()
    {
        return $this->hasOne('App\Models\CheckQuestion', 'id', 'check_questions_id');
    }

}

resources/views/checkanswers/create.blade.php
@extends('layouts.main')

@section('content')

    <div class="page-heading">
        <h3>{{ __('จัดการจุดตรวจ') }}</h3>
        <div class="pull-right">
            <a class="btn btn-success" href="{{ route('answers.index',$loadm->id) }}"><i class="bi bi-backspace-fill"></i> ย้อนกลับ</a>
        </div>
    </div>
    <div class="page-content">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">{{ __('บันทึกข้อมูล') }}</div>

                    <div class="card-body">
                        <form method="POST" action="{{ route('answers.store',$loadm->id) }}" enctype="multipart/form-data" >

                            @csrf
                            <input type="hidden" name="location" value="{{$location}}"/>
                            @foreach ($checkset->checkquestions()->orderBy('seq','ASC')->get() as $item)
                            <div class="form-product row">
                                <label for="question-{{$item->id}}" class="col-md-2 col-form-label text-md-right">{{ $item->name }}</label>

                                <div class="col-md-4">
                                    @if ($item->type_question == 'TEXT' )
                                        <input id="question-{{$item->id}}" type="text" class="form-control @error('question-'.$item->id) is-invalid @enderror"
                                        name="question-{{$item->id}}"

                                        @if($item->name == 'ชื่อ')
                                            value="{{ $uploaddeliveryplan->driver1 ?? old('question-'.$item->id) }}"
                                        @else
                                            value="{{ old('question-'.$item->id) }}"
                                        @endif

                                        @if ($item->required_flag == 'Y')
                                            required
                                        @endif


                                        >
                                    @else
                                     @if ($item->type_question == 'IMAGE' )
                                        <input type="file" accept="image/*;capture=camera" capture="camera" name="question-{{$item->id}}"
                                        @if ($item->required_flag == 'Y')
                                            required
                                        @endif
                                        >
                                    @else
                                        <textarea id="question-{{$item->id}}" class="form-control @error('question-'.$item->id) is-invalid @enderror"
                                        name="question-{{$item->id}}"
                                        @if ($item->required_flag == 'Y')
                                            required
                                        @endif
                                        >{{ old('question-'.$item->id) }}</textarea>
                                    @endif
                                    @endif


                                    @error('question-'.$item->id)
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>

                            </div>
                            @endforeach

                            <div class="form-product row mb-0">
                                <div class="col-md-6 offset-md-2">
                                    <button type="submit" class="btn btn-primary">
                                        {{ __('Create') }}
                                    </button>
                                </div>
                            </div>


                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/checkanswers/edit.blade.php
@extends('layouts.main')

@section('content')

    <div class="page-heading">
        <h3>{{ __('จัดการจุดตรวจ') }}</h3>
        <div class="pull-right">
            <a class="btn btn-success" href="{{ route('answers.show',[$loadm->id,$checkanswer->id]) }}"><i class="bi bi-backspace-fill"></i> ย้อนกลับ</a>
        </div>
    </div>
    <div class="page-content">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">{{ __('บันทึกข้อมูล') }}</div>

                    <div class="card-body">
                        <form method="POST" action="{{ route('answers.update',[$loadm->id,$checkanswer->id]) }}" enctype="multipart/form-data" >
                            @method('PUT')
                            @csrf
                            <input type="hidden" name="location" value="{{ $checkanswer->location}}"/>
                            <div class="form-product row">
                                <label for="question-{{$checkanswer->id}}" class="col-md-2 col-form-label text-md-right">{{ $checkanswer->checkquestion->name }}</label>
                                @php
                                    $columnanswer1 = $checkanswer->ans1_column;
                                    $columnanswer2 = $checkanswer->ans2_column;
                                    $columnanswer3 = $checkanswer->ans3_column;
                                @endphp
                                <div class="col-md-4">
                                    @if ($checkanswer->type_question == 'TEXT' )
                                        <input id="question-{{$checkanswer->id}}" type="text" class="form-control @error('question-'.$checkanswer->id) is-invalid @enderror"
                                        name="question-{{$checkanswer->id}}" value="{{ $checkanswer->$columnanswer1 }}"
                                        @if ($checkanswer->required_flag == 'Y')
                                            required
                                        @endif
                                        >
                                    @else
                                     @if ($checkanswer->type_question == 'IMAGE' )
                                        <input type="file" accept="image/*;capture=camera" name="question-{{$checkanswer->id}}"
                                        @if ($checkanswer->required_flag == 'Y')
                                            required
                                        @endif
                                        ><br/>
                                        <img src="{{ url($checkanswer->$columnanswer3) }}" width="200px" >
                                    @else
                                        <textarea id="question-{{$checkanswer->id}}" class="form-control @error('question-'.$checkanswer->id) is-invalid @enderror"
                                        name="question-{{$checkanswer->id}}"
                                        @if ($checkanswer->required_flag == 'Y')
                                            required
                                        @endif
                                        >{{ $checkanswer->$columnanswer1 }}</textarea>
                                    @endif
                                    @endif


                                    @error('question-'.$checkanswer->id)
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>

                            </div>

                            <div class="form-product row mb-0">
                                <div class="col-md-6 offset-md-2">
                                    <button type="submit" class="btn btn-primary">
                                        {{ __('Edit') }}
                                    </button>
                                </div>
                            </div>


                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/checkanswers/index.blade.php
@extends('layouts.main')

@section('content')
    @if(Session::has('success'))
        <div><h3> {{ Session::get('success') }}</h3></div>
    @endif
    @if(Session::has('error'))
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            <strong>{{ Session::get('error') }}</strong>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    @endif
    <div class="page-heading">
        <h3>{{ __('จัดการจุดตรวจ') }}</h3>
    </div>
    <div class="page-content">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <a class="btn btn-success" href="{{ route('answers.scan',$loadm->id) }}"><i class="bi bi-camera-fill"></i> แสกนคิวอาร์โค๊ด</a>
                    </div>
                    <div class="p-2">
                    <form method="GET" action="{{ route('answers.index',$loadm->id) }}" accept-charset="UTF-8" class="form-inline my-2 my-lg-0 float-right" role="search">
                            <div class="input-group">
                                <input type="text" class="form-control" name="search" placeholder="Search..." value="{{ request('search') }}">
                                <span class="input-group-append">
                                    <button class="btn btn-secondary" type="submit">
                                        Search
                                    </button>
                                </span>
                            </div>
                        </form>
                    </div>
                    <div class="card-body">
                        @if ($message = Session::get('success'))
                            <div class="alert alert-success">
                                <p>{{ $message }}</p>
                            </div>
                        @endif

                        <table class="table table-bordered">
                            <tr><th>วันเวลา</th>
                                <th>จุดตรวจ</th>
                                <th>จำนวน</th>
                                <th>status</th>
                                <th></th>
                            </tr>
                            @foreach ($checkanswers as $checkanswer)
                                <tr>
                                    <td>{{ $checkanswer->created_at }}</td>
                                    <td>{{ $checkanswer->checkpoint->name }}</td>
                                    <td>{{ $checkanswer->checkanswers->count()}}</td>
                                    <td>{{ $checkanswer->status }}</td>
                                    <td>
                                        <a class="btn btn-info" href="{{ route('answers.show',[$loadm->id, $checkanswer->id]) }}">แสดงข้อมูล</a>
                                        <a class="btn btn-primary" href="{{ route('answers.edit', [$loadm->id, $checkanswer->id]) }}">แก้ไข</a>
                                        <form action="{{ route('answers.destroy', [$loadm->id, $checkanswer->id]) }}" method="POST">
                                            @csrf
                                            @method('DELETE')
                                            <button type="submit" class="btn btn-danger">ลบ</button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                        </table>
                        <div class="pagination-wrapper"> {!! $checkanswers->appends(['search' => Request::get('search')])->render() !!} </div>
                    </div>
                </div>
            </div>
        </div>
    </div>




@endsection

resources/views/checkanswers/scan.blade.php
@extends('layouts.mainscan')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-12">
                SCAN
            </div>
            <div class="col-12">
                <div id="reader" width="600px">
                </div>
            </div>
        </div>
    </div>
    @endsection

resources/views/checkanswers/view.blade.php
@extends('layouts.main')

@section('content')
    @if(Session::has('success'))
        <div><h3> {{ Session::get('success') }}</h3></div>
    @endif
    @if(Session::has('error'))
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            <strong>{{ Session::get('error') }}</strong>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    @endif
    <div class="page-heading">
        <h3>{{ __('จัดการ CROP') }}</h3>
    </div>
    <div class="page-content">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <a class="btn btn-success" href="{{ route('answers.scan',$loadm->id) }}">เก็บข้อมูล</a>
                    </div>
                    <div class="p-2">
                    <form method="GET" action="{{ route('crops.index') }}" accept-charset="UTF-8" class="form-inline my-2 my-lg-0 float-right" role="search">
                            <div class="input-group">
                                <input type="text" class="form-control" name="search" placeholder="Search..." value="{{ request('search') }}">
                                <span class="input-group-append">
                                    <button class="btn btn-secondary" type="submit">
                                        Search
                                    </button>
                                </span>
                            </div>
                        </form>
                    </div>
                    <div class="card-body">
                        @if ($message = Session::get('success'))
                            <div class="alert alert-success">
                                <p>{{ $message }}</p>
                            </div>
                        @endif

                        <table class="table table-bordered">
                            <tr>
                                <th>จุดตรวจ</th>
                                <th>จำนวน</th>
                                <th></th>
                            </tr>
                            @foreach ($checkansm->checkanswers as $checkanswer)
                                <tr>
                                    <td>{{ $checkanswer->checkquestion->name }}</td>
                                    @php
                                        $columnanswer1 = $checkanswer->ans1_column;
                                        $columnanswer2 = $checkanswer->ans2_column;
                                        $columnanswer3 = $checkanswer->ans3_column;
                                    @endphp
                                    @if ($checkanswer->type_question == 'IMAGE')
                                        <td><img src="{{ url($checkanswer->$columnanswer3) }}" width="200px" ></td>
                                    @else
                                    @if ($columnanswer1 == 'custom_f_1')
                                        <td>{{ number_format($checkanswer->$columnanswer1,2) }}</td>
                                    @else
                                         <td>{{ $checkanswer->$columnanswer1 }}</td>   
                                    @endif
                                        
                                    @endif


                                    <td>
                                        <a class="btn btn-primary" href="{{ route('answers.edit', [$loadm->id, $checkanswer->id]) }}">แก้ไข</a>

                                    </td>
                                </tr>
                            @endforeach
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>




@endsection