routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ProductsController;
use App\Http\Controllers\GroupsController;
use App\Http\Controllers\LoadingsController;
use App\Http\Controllers\TeamsController;
use App\Http\Controllers\BrokenTypesController;
use App\Http\Controllers\ContainerTypeController;
use App\Http\Controllers\CustomerTypesController;
use App\Http\Controllers\ReportsController;
use App\Http\Controllers\MasterPlansController;
use App\Http\Controllers\UsersController;
use App\Http\Controllers\ShipPlansController;
use App\Http\Controllers\ListLoadController;
use App\Http\Controllers\ListLoadDetController;
use App\Http\Controllers\CropsController;
use App\Http\Controllers\ExtWhsController;
use App\Http\Controllers\LoadingCarriesController;
use App\Http\Controllers\CheckPointsController;
use App\Http\Controllers\CheckSetsController;
use App\Http\Controllers\CheckQuestionsController;
use App\Http\Controllers\CheckAnswersController;
use App\Http\Controllers\DriversController;
use App\Http\Controllers\UploadDeliveryPlansController;
use App\Http\Controllers\CheckPointPublicController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/checkscan', [CheckPointPublicController::class, 'scan']);


Route::get('/', [LoadingsController::class, 'list']);

Route::get('/userdatas/changepass', [UsersController::class, 'changepass'])->name('userdatas.changepass');
Route::post('/userdatas/changepassAction', [UsersController::class, 'changepassAction'])->name('userdatas.changepassaction');
Route::get('/user_importView', [UsersController::class, 'importExportView'])->name('user_importView');
Route::post('/userdatas/import', [UsersController::class, 'import'])->name('user_import');
Route::resource('userdatas', UsersController::class);
Route::get('/product_importView', [ProductsController::class, 'importExportView'])->name('product_importView');
Route::post('/products/import', [ProductsController::class, 'import'])->name('product_import');
Route::get('/products/getbyid/{id}', [ProductsController::class, 'getById'])->name('products.getById');
Route::get('/drivers', [DriversController::class, 'index'])->name('drivers.index');
Route::resource('uploaddeliveryplans', UploadDeliveryPlansController::class);


Route::prefix('admin')->group(function () {
    Route::get('check_points/qrcode', [CheckPointsController::class, 'qrcode'])->name('check_points.qrcode');
    Route::resource('check_points', CheckPointsController::class);
    Route::resource('check_sets', CheckSetsController::class);
    Route::prefix('{check_set_id}')->group(function () {
        Route::resource('check_questions', CheckQuestionsController::class);
    });
});

Route::prefix('chkpoint/{loading_id}')->group(
    function () {
        Route::get('answers/scan', [CheckAnswersController::class,'scan'])->name('answers.scan');
        Route::get('answers/createall', [CheckAnswersController::class, 'createAll'])->name('answers.createAll');
        Route::post('answers/storeall', [CheckAnswersController::class, 'storeAll'])->name('answers.storeAll');
        Route::resource('answers', CheckAnswersController::class);
});

Route::resource('products', ProductsController:: class);
Route::resource('crops', CropsController::class);
Route::resource('ext_whs', ExtWhsController::class);
Route::resource('groups', GroupsController::class);
Route::resource('planships', ShipPlansController::class);
Route::get('/team_importView', [TeamsController::class, 'importExportView'])->name('team_importView');
Route::post('/teams/import', [TeamsController::class, 'import'])->name('team_import');
Route::resource('teams', TeamsController::class);
Route::resource('broken-types', BrokenTypesController::class);
Route::resource('customer-types', CustomerTypesController::class);
Route::resource('container-types', ContainerTypeController::class);

Route::get('/master-plans/createdetail/{master_plan_m_id}', [MasterPlansController::class, 'createdetail'])->name('master-plans.createdetail');
Route::post('/master-plans/createdetailAction/{master_plan_m_id}', [MasterPlansController::class, 'createdetailAction'])->name('master-plans.createdetailAction');
Route::get('/master-plans/editdetail/{id}', [MasterPlansController::class, 'editdetail'])->name('master-plans.editdetail');
Route::post('/master-plans/editdetailAction/{id}', [MasterPlansController::class, 'editdetailAction'])->name('master-plans.editdetailAction');
Route::get('/master-plans/deletedetail/{id}', [MasterPlansController::class, 'deletedetail'])->name('master-plans.deletedetail');

Route::resource('master-plans', MasterPlansController::class);

Route::get('/loadings', [LoadingsController::class, 'list'])->name('loadings.index');
Route::get('/loadings/create', [LoadingsController::class, 'create'])->name('loadings.create');
Route::post('/loadings/createAction', [LoadingsController::class, 'createAction'])->name('loadings.createaction');
Route::get('/loadings/edit/{id}', [LoadingsController::class, 'edit'])->name('loadings.edit');
Route::post('/loadings/editAction/{id}', [LoadingsController::class, 'editAction'])->name('loadings.editaction');
Route::get('/loadings/show/{id}', [LoadingsController::class, 'show'])->name('loadings.show');
Route::get('/loadings/realtime/{id}', [LoadingsController::class, 'realtime'])->name('loadings.realtime');
Route::get('/loadings/realtimeno/{id}', [LoadingsController::class, 'realtimeno'])->name('loadings.realtimeno');
Route::get('/loadings/sent_mail', [LoadingsController::class, 'sent_mail'])->name('loadings.sent_mail');
Route::get('/loadings/sent_mail_extImage', [LoadingsController::class, 'sent_mail_extImage'])->name('loadings.sent_mail_extImage');

// Route::get('/loadings/downloadPDF/{id}', [LoadingsController::class, 'downloadPDF'])->name('loadings.downloadPDF');
Route::post('/loadings/load_reason', [LoadingsController::class, 'load_reason'])->name('loadings.load_reason');
Route::get('/loadings/clone/{id}', [LoadingsController::class, 'clone'])->name('loadings.clone');
Route::post('/loadings/cloneAction/{id}', [LoadingsController::class, 'cloneAction'])->name('loadings.cloneAction');

Route::get('/loadings/getrealcounter/{id}', [LoadingsController::class, 'getrealcounter'])->name('loadings.getrealcounter');
Route::get('/loadings/edit/{id}', [LoadingsController::class, 'edit'])->name('loadings.edit');
Route::get('/loadings/delete/{id}', [LoadingsController::class, 'delete'])->name('loadings.destroy');
Route::get('/loadings/planload/{id}', [LoadingsController::class, 'planload'])->name('loadings.planload');
Route::post('/loadings/planloadAction/{id}', [LoadingsController::class, 'planloadAction'])->name('loadings.planloadaction');
Route::get('/loadings/createdetail/{id}', [LoadingsController::class, 'createdetail'])->name('loadings.createdetail');
Route::post('/loadings/createdetailAction/{id}', [LoadingsController::class, 'createdetailAction'])->name('loadings.createdetailaction');
Route::get('/loadings/editdetail/{id}', [LoadingsController::class, 'editdetail'])->name('loadings.editdetail');
Route::post('/loadings/editdetailAction/{id}', [LoadingsController::class, 'editdetailAction'])->name('loadings.editdetailaction');
Route::get('/loadings/deletedetail/{id}', [LoadingsController::class, 'deletedetail'])->name('loadings.deletedetail');
Route::get('/loadings/planloadview/{id}', [LoadingsController::class, 'planloadview'])->name('loadings.planloadview');
Route::get('/loadings/changestage/{id}/{stage}', [LoadingsController::class, 'changestage'])->name('loadings.changestage');
Route::get('/loadings/entersection1/{id}', [LoadingsController::class, 'entersection1'])->name('loadings.entersection1');
Route::post('/loadings/entersection1Action/{id}', [LoadingsController::class, 'entersection1Action'])->name('loadings.entersection1action');
Route::get('/loadings/entersection2/{id}', [LoadingsController::class, 'entersection2'])->name('loadings.entersection2');
Route::post('/loadings/entersection2Action/{id}', [LoadingsController::class, 'entersection2Action'])->name('loadings.entersection2action');
Route::get('/loadings/entersection3/{id}', [LoadingsController::class, 'entersection3'])->name('loadings.entersection3');
Route::post('/loadings/entersection3Action/{id}', [LoadingsController::class, 'entersection3Action'])->name('loadings.entersection3action');
Route::get('/loadings/entersection4/{id}', [LoadingsController::class, 'entersection4'])->name('loadings.entersection4');
Route::post('/loadings/entersection4Action/{id}', [LoadingsController::class, 'entersection4Action'])->name('loadings.entersection4action');
Route::get('/loadings/closeload/{id}', [LoadingsController::class, 'closeload'])->name('loadings.closeload');
Route::get('/loadings/usemasterplan/{id}', [LoadingsController::class, 'usemasterplan'])->name('loadings.usemasterplan');
Route::post('/loadings/usemasterplanAction/{id}', [LoadingsController::class, 'usemasterplanAction'])->name('loadings.usemasterplanaction');
Route::get('/loadings/entercountermanual/{id}', [LoadingsController::class, 'entercountermanual'])->name('loadings.entercountermanual');
Route::post('/loadings/entercountermanualAction/{id}', [LoadingsController::class, 'entercountermanualAction'])->name('loadings.entercountermanualAction');
Route::get('/loadings/search', [LoadingsController::class, 'searchLoading'])->name('loadings.search');
Route::get( '/loadings/searchview/{id}', [LoadingsController::class, 'viewLoadingData'])->name('loadings.searchview');
Route::get('/loadings/searchviewextimage/{id}', [LoadingsController::class, 'viewLoadingDataExtImage'])->name('loadings.searchviewextimages');

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    use HasFactory;

    protected $fillable = [
        'name','desc', 'boxcode', 'bagcode',
        'wide','long','height', 'wide_er', 'long_er', 'height_er',
        'weight','note',
        'customer', 'numperbox', 'bagweight', 'underboxcode',
        'bundelnumber',
        'desc_list',
        'lot_load_no',
        'lot_load_name'
    ];

    public function loadsorts()
    {
        return $this->hasMany('App\Models\ListLoadSort', 'product_id');
    }
}

resources/views/products/err_import.blade.php
@extends('layouts.main')

@section('content')
    {{-- @if(Session::has('error'))
        <div><h3> {{ Session::get('error') }}</h3></div>
    @endif --}}
    <div class="page-heading">
        <h3>{{ __('สินค้าที่ upload ไม่ได้') }}</h3>
        <div class="pull-right">
            <a class="btn btn-success" href="{{ route('products.index') }}">Back</a>
        </div>
    </div>
    <div class="page-content">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                    </div>
                    <div class="card-body">

                        <table class="table table-bordered">
                            <tr>
                                <th>บรรทัดที่</th>
                                <th>สินค้า</th>
                                <th>รายละเอียด</th>
                            </tr>
                            @foreach ($sort_product as $product)
                                <tr>
                                    <td>{{ $product['sort'] }}</td>
                                    <td>{{ $product['product'] }}</td>
                                    <td>{{ $product['note'] }}</td>                                    
                                </tr>
                            @endforeach
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>




@endsection

resources/views/products/import.blade.php
@extends('layouts.main')

@section('content')
    @if(Session::has('error'))
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            <strong>{{ Session::get('error') }}</strong>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    @endif
    <div class="page-heading">
        <h3>{{ __('Products - Import') }}</h3>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    
                    {{-- <div class="card-header">Questions - Import</div> --}}
                    <div class="card-body">
                        <div class="pull-right">
                            <a class="btn btn-success" href="{{ route('products.index') }}">Back</a>
                        </div>
                        <br/>
                        <div class="row g-4 settings-section">
	                
                            <div class="col-12 col-md-12">
                                <div class="app-card app-card-settings shadow-sm p-4">
                                    
                                    <div class="app-card-body">
                                        <form action="{{ route('product_import') }}" method="POST" enctype="multipart/form-data">
                                            @csrf
                                            <div class="form-group mb-4" style="max-width: 500px; margin: 0 auto;">
                                                <div class="custom-file text-left">
                                                    <input type="file" name="file_upload" class="custom-file-input" id="file_upload">
                                                </div>
                                            
                                                <br>
                                                <button class="btn btn-success">Import</button>
                                                {{-- <a class="btn btn-warning" href="{{ route('quiz_export') }}">Export</a> --}}
                                                <div class="col-auto" style="float: right; margin-right: 10%; width:50%"><a href="{{ asset('assets/product.xlsx') }}">ตัวอย่างไฟล์..</a></div>
                                            </div>
                                        </form>  
                                    </div><!--//app-card-body-->
                                    
                                </div><!--//app-card-->
                            </div>
                        </div><!--//row-->

                        {{-- <hr class="my-4">
                        <div class="row g-4 settings-section">
                            <h1 class="app-page-title">ตัวอย่างสำหรับการ Import</h1>
                            <img src="{{asset('/pic/quiz.jpg')}}"  class="photo" width="100" height="250" data-toggle="modal" data-target="#exampleModal">
                        </div><!--//row-->  --}}

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/products/index.blade.php
@extends('layouts.main')

@section('content')
    @if(Session::has('success'))
        <div><h3> {{ Session::get('success') }}</h3></div>
    @endif
    @if(Session::has('error'))
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            <strong>{{ Session::get('error') }}</strong>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    @endif
    <div class="page-heading">
        <h3>{{ __('จัดการสินค้า') }}</h3>
    </div>
    <div class="page-content">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <a class="btn btn-success" href="{{ route('products.create') }}">สร้างสินค้าใหม่</a>
                        <a class="btn btn-success" href="{{ route('product_importView') }}">Upload</a>
                    </div>
                    
                    <form method="GET" action="{{ route('products.index') }}" accept-charset="UTF-8" class="form-inline my-2 my-lg-0 float-right" role="search">
                            <div class="input-group">
                                <input type="text" class="form-control" name="search" placeholder="Search..." value="{{ request('search') }}">
                                <span class="input-group-append">
                                    <button class="btn btn-secondary" type="submit">
                                        Search
                                    </button>
                                </span>
                            </div>
                        </form>
                    <div class="card-body">
                        @if ($message = Session::get('success'))
                            <div class="alert alert-success">
                                <p>{{ $message }}</p>
                            </div>
                        @endif

                        <table class="table table-bordered">
                            <tr>
                                <th>ชื่อ</th>
                                <th>รายละเอียด กว้าง/ยาว/สูง/น้ำหนัก</th>
                                <th></th>
                            </tr>
                            @foreach ($products as $product)
                                <tr>
                                    <td>{{ $product->name }}</td>
                                    <td>{{ number_format($product->wide, 2, '.', ',') ?? '-' }} / {{ number_format($product->long , 2, '.', ',') ?? '-' }} / {{ number_format($product->height  , 2, '.', ',') ?? '-' }} / {{ number_format($product->weight , 2, '.', ',')  ?? '-' }}</td>
                                    <td>
                                        <a class="btn btn-info" href="{{ route('products.show', $product->id) }}">แสดงข้อมูล</a>
                                        <a class="btn btn-primary" href="{{ route('products.edit', $product->id) }}">แก้ไข</a>
                                        {{-- <a class="btn btn-danger" href="{{ route('products.destroy', $product->id) }}">ลบ</a> --}}
                                        <form action="{{ route('products.destroy', $product->id) }}" method="POST">

                                            @csrf
                                            @method('DELETE')
                                            <button type="submit" class="btn btn-danger">ลบ</button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                        </table>
                        <div class="pagination-wrapper"> {!! $products->appends(['search' => Request::get('search')])->render() !!} </div>
                    </div>
                </div>
            </div>
        </div>
    </div>




@endsection

resources/views/products/view.blade.php
@extends('layouts.main')

@section('content')

    <div class="page-heading">
        <h3>{{ __('จัดการสินค้า') }}</h3>
        <div class="pull-right">
            <a class="btn btn-success" href="{{ route('products.index') }}">Back</a>
        </div>
    </div>
    <div class="page-content">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">{{ __('แสดงข้อมุลสินค้า') }}</div>

                    <div class="card-body">
                        @if ($message = Session::get('success'))
                            <div class="alert alert-success">
                                <p>{{ $message }}</p>
                            </div>
                        @endif

                        <table class="table table-bordered">
                            <tr>
                                <th>รหัสสินค้า</th>
                                <td>{{ $product->name }}</td>
                            </tr>
                            <tr>
                                <th>รหัสกล่อง</th>
                                <td>{{ $product->boxcode }}</td>
                            </tr>
                            <tr>
                                <th>รหัสถุง</th>
                                <td>{{ $product->bagcode }}</td>
                            </tr>
                            <tr>
                                <th>Desc</th>
                                <td>{{ $product->desc }}</td>
                            </tr>
                            <tr>
                                <th>กว้าง (cm)</th>
                                <td>{{ $product->wide }}</td>
                            </tr>
                            <tr>
                                <th>ยาว (cm)</th>
                                <td>{{ $product->long }}</td>
                            </tr>
                            <tr>
                                <th>สูง (cm)</th>
                                <td>{{ $product->height }}</td>
                            </tr>
                            <tr>
                                <th>หนัก (kg)</th>
                                <td>{{ $product->weight }}</td>
                            </tr>
                            <tr>
                                <th>Note</th>
                                <td>{{ $product->note }}</td>
                            </tr>
                            <tr>
                                <th>Action</th>
                                <td>
                                    <a class="btn btn-primary" href="{{ route('products.edit', $product->id) }}">แก้ไข</a>
                                    <form action="{{ route('products.destroy', $product->id) }}" method="POST">

                                        @csrf
                                        @method('DELETE')
                                        <button type="submit" class="btn btn-danger">ลบ</button>
                                    </form>
                                </td>
                            </tr>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>




@endsection